version: 2
jobs:
  build:
    working_directory: ~/go/src/github.com/prasannamahajan/circleci-tut1
    machine: true
   # docker:
   #   - image: circleci/golang:1.9
    steps:
      - checkout
      - run:
          name: Build
          command: 'go build -o sum'
  test:
    machine: true
  #  docker:
  #    - image: circleci/golang:1.9
    steps:
      - checkout
      - run:
          name: Test
          command: go test -v
  deploy:
    machine: true
  #  docker:
  #    - image: circleci/golang:1.9
    steps:
      - checkout
      - run:
          name: Deploy
          command: echo "Deployed"

workflows:
  version: 2
  api_server:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master