version: 2
jobs:
  build:
    machine: true
    working_directory: /go/src/github.com/prasannamahajan/circleci-tut1
    steps:
      - checkout
      - run: go build -o sum
  test:
    machine: true
    steps:
      - checkout
      - run: go test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test