version: 2
jobs:
  build:
    docker:
      - image: circleci/go:1.9
    steps:
      - checkout
      - run: go build -o sum
  test:
    docker:
      - image: circleci/go:1.9
    steps:
      - checkout
      - run: go test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test