version: 2
jobs:
  build-job:
    steps:
      - checkout
      - run:
          name: Build 
          command: |
            git build -o sum
      - run:
	  name: Test
	  command: |
	    go test -v

  deploy-job:
    steps:
      - checkout
      - run:
          name: Deploy to GKE
          command: |
            ./sum

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master

